### PR TITLE
inline style/image on /#hello

### LINKED ISSUE #2703: Flashes of older content in the onboarding flow
@johngruen reported this, to confirm.

### PR DESCRIPTION
**Pull request by dannycoates**
I can't repro that video, but i guess we could embed the style and image in the html.

fixes #2703

### CODE REVIEW

**Comment by dannycoates** [comment]
or maybe its already fixed and we can just close

**Comment by ianb** [comment]
I think the missing styles referred to the slides, not the homepage

**Comment by dannycoates** [comment]
> I think the missing styles referred to the slides, not the homepage

according to john's video in #2703 it was the page

**Comment by ianb** [comment]
Oh huh.  I don't know why/how/if styles are normally applied to pages – it seems like this would happen often, but I never notice it?  If we really wanted to inline styles then we'd want to use fs.readFileSync to load the content, and not inline it into view.js.

**Comment by dannycoates** [comment]
@johngruen or anyone. Can you reproduce the unstyled content since we updated the default page? (I can't) https://screenshots.firefox.com

I'd prefer to just close this.

**Comment by johngruen** [comment]
pulling down now!

**Comment by johngruen** [comment]
LGTM!

**Pull request merged**
