### PR TITLE
Fixes #4680 - Text width should not extend beyond 5px inside canvas

### LINKED ISSUE #4680: [Annotations] Text width should not extend beyond 5px inside canvas
After playing with the canvas, i think we need to adjust the max string length so that text input cannot exceed the width of the canvas - 10px (5 on each side)

Now there's an edge case where the user could type longer strings with a small font and then resize, but i think that's OK

### PR DESCRIPTION
**Pull request by punamdahiya**
Fixes #4680

### CODE REVIEW

**Comment by chenba** [comment]
Having a limit based on character count doesn't work very well.  If I enter a bunch of `Q`s [0], delete them, and enter `i`s, the limit is way too low.

[0] In my particular shot, the first `Q` got chopped off: 
image

**Comment by punamdahiya** [comment]
@chenba good catch! updated PR to remove maxlength attribute and use hidden div to enforce text content limit when text input width exceeds canvas. Please review

**Comment by chenba** [comment]
The issue with the first character being clipped in the input still exists:

q-before

(This depends on the combination of shot width and text content; it doesn't happen every time.)

And then the text shifts to the right so the first character is displayed in its entirety on confirm:

q-after

**Comment by punamdahiya** [comment]
@chenba updated PR to account for padding on both sides before enforcing text content limit which for some character sizes results in less character but better experience than clipped. Please review. Thanks!

**Comment by chenba** [comment]
The limit works great.  There's still a small problem with the alignment.  If I reach the limit by entering characters starting at the default position, there's an empty margin on the left but not the right.  This is the yellow line with the stars in the image below.  The width of the empty margin depends on the text entered.

If I drag the text around after reaching the limit, then I would encounter the edge limit.  This is the green line in the image below.

I'll leave it up to you if you want to fix it in this PR or open another issue for it.  It's a pretty small bug.

image

**Comment by punamdahiya** [comment]
Thanks @chenba,  looks like need to debug and adjust left position when text content reaches max limit which I will prefer to triage and fix as separate bug

**Pull request merged**
