### PR TITLE
Fix #3718, send a response after incrementing counts

### LINKED ISSUE #3718: Screenshots overlay does not come up in Firefox Developer Edition with latest development addon
Setup/Env

- Firefox Developer Edition 57.0b13
- Linux
- `master` branch (rev `1450218` at the time of writing)

STR

- Run addon with `bin/run-addon`.  Do _not_ use the `--webextension` flag.
- Go to a web page.
- Select Take a Screenshot from the Page actions.

Actual Result

- No Screenshots UI

Expected Result

- Screenshots UI displayed

Note: This is _not_ reproducible on Nightly (58.0a1 on Windows or Linux).

### PR DESCRIPTION
**Pull request by 6a68**
@chenba Mind giving this a try? After applying this patch, dev edition should still complain about an "unknown scalar", but should otherwise work

### CODE REVIEW

**Comment by chenba** [comment]
👍

**Comment by chenba** [comment]
CI test fail is not a fluke this time. :(  Running `npm run test` locally with Nightly being the browser, I get the same failure.  It passes when Developer edition is used.

**Comment by 6a68** [comment]
;_; thanks, I'll take a look

**Comment by 6a68** [comment]
Barry pointed out that master's busted, and this is a fairly awful bug, so, merging

**Pull request merged**
