### PR TITLE
DO NOT MERGE Fix #2843, lazily load code into the background page

### LINKED ISSUE #2843: Lazy load our background page code
From https://bugzilla.mozilla.org/show_bug.cgi?id=1361792#c31 :

> After some further investigation, it looks like a lot of the startup responsiveness issues are caused by loading a huge amount of code into the Screenshots background page at startup. It would help a lot if the add-on lazily loaded its background page code when first needed (something like require.js might be a good idea), and avoided touching extension APIs before absolutely necessary.

It looks like this is taking 150-200ms at startup

### PR DESCRIPTION
**Pull request by ianb**
This takes a minimal approach, loading scripts using the script tag on the first button click.

### CODE REVIEW

**Comment by ianb** [comment]
It occurs to me that this might integrate badly with wantsauth and the sitehelper – sitehelper could be loaded when the background page is not, and so if it tries to communicate that might fail.

**Comment by 6a68** [comment]
> It occurs to me that this might integrate badly with wantsauth and the sitehelper – sitehelper could be loaded when the background page is not, and so if it tries to communicate that might fail.

@ianb what additional steps would be needed to make this fully functional?

**Comment by ianb** [comment]
I could make the background page load itself on any message. It wouldn't be too hard to do.

**Comment by ianb** [comment]
Closing, as this does not seem to help much

**Pull request closed without merging**
