### PR TITLE
Fix #2695, expand Selenium test

### LINKED ISSUE #2695: Expand Selenium test
The test in `test/test.js` should be updated to test the actual functionality.

We want to run a test that:

- [x] Invokes Screenshots
- [x] Makes a selection, or maybe just hits "Save Visible"
- [x] Uses the homepage as its page to make a selection from
- [x] Confirms that the tab opens, is updated to the shot page
- [ ] Notices any `console.error` or `console.warn` messages
- [ ] Maybe notices the exact sequence of `sendEvent` calls (many of the results can be confirmed this way, instead of trying to detect items in the interface itself)
- [ ] Extra points: load My Shots and make sure it is authenticated

### PR DESCRIPTION
**Pull request by ianb**
Implement a test that invokes Screenshots, skips onboarding, clicks the Visible save button, and confirms that a new tab is opened to a shot page.

### CODE REVIEW

**Comment by ianb** [comment]
Currently, on Nightly, the test installation process does not overwrite the built-in version of the add-on.  You can see this because of a failure that it opens a page on screenshots.firefox.com instead of localhost:10080.  I'm not sure why, though I see this error in the Browser Console:

image

It seems to claim that it is overwriting the add-on, but then there's the error.  I recall this error from #2655, and @kmaglione said it was not a problem there, but maybe it means something in this case.

Though CircleCI is *not* showing this error, it actually seems to be working okay, except that the server isn't available locally (maybe fixed by ce5f4469e78a85c7b14e421142b08ea070e2b8ea)

**Comment by 6a68** [comment]
I can't find the error now, but I'm pretty sure I saw an error in today's nightly about failing to update system addons. Can you repro this on dev edition or a slightly older Nightly?

**Comment by 6a68** [comment]
Hmm, here's a bug about system addons not getting updated, but it's labeled as fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1350064

Maybe ping rhelmer to see if this is a known issue?

**Comment by rhelmer** [comment]
We chatted about this in IRC - the tl;dr is that bug 1350064 is unrelated (it's about updates sticking around after application upgrade) - the problem is that the WebExtension started by the built-in add-on is not shut down when the bootstrapped add-on is.

I tested this locally and stopping the WebExtension on bootstrap.js `shutdown()` seems to do the trick.

**Pull request merged**
