### PR TITLE
add context fill icons

### PR DESCRIPTION
**Pull request by johngruen**
Please note, this is dependent on https://bugzilla.mozilla.org/show_bug.cgi?id=1379464

### CODE REVIEW

**Comment by 6a68** [comment]
added a lil comment so this doesn't get merged in a flurry of PR queue clearing

**Comment by ianb** [comment]
Landing details have been figured out

**Comment by msujaws** [comment]
Why did the filenames have to change to add "-v2"? We should have been able to keep the old filenames, right?

**Comment by johngruen** [comment]
@msujaws yes most likely, but i was encoutering some caching issues with the old icons while testing so i changed the names in order to pick up the diff.

**Comment by msujaws** [comment]
probably needed to run `./mach build` instead of `./mach build faster` to fix the caching issue. i've seen that before with changes to the pocket system addon

**Comment by ianb** [comment]
Our normal development process sideloads the add-on via `web-ext`, so @johngruen doesn't typically use mach.

**Comment by johngruen** [comment]
@msujaws jaws, maybe so. would you prefer i revert the names or leave as is?

**Comment by msujaws** [comment]
well, it's your project so do as you wish, but building version numbers in to filenames is doing a job that our version control system already does :)

**Comment by johngruen** [comment]
got it. let's keep it as since it's make-work to revert it now. The -v2 will stand as a memorial of what's happened here :)

**Pull request merged**
