### PR TITLE
Fix/2175 (Work in Progress)

### PR DESCRIPTION
**Pull request by niharikak101**
This is a fix for #2175 

As of now it shows 'loading...' text while the image loads, but we could replace that with a spinner. 
Thoughts on the approach?

### CODE REVIEW

**Comment by niharikak101** [comment]
Found some loaders at http://loading.io/ and added one as a placeholder!

**Comment by dannycoates** [comment]
Hi @niharikak101, I think you're on the right track. Your `state`, render function, and spinner look good. 

I think we're going to need to do more than check the image in `componentDidMount` for this to work consistently. It works now sometimes (maybe every time when the server is on your computer), but the tricky thing is that the image *DOM element* being rendered (which triggers `componentDidMount`) and the image *data* being loaded don't always happen around the same time. We don't get another call to `componentDidMount` once the image data is loaded, so we need something else to change the `state`.

I think this post explains what we need to do pretty well: http://andrewhfarmer.com/detect-image-load/

**Comment by niharikak101** [comment]
@dannycoates understood! :) Thank you!

**Comment by dannycoates** [comment]
The code looks great! I'll defer to @johngruen on the spinner...

spinner

**Comment by ianb** [comment]
I opened #2576 as a follow-up to maybe animate the spinner.

**Pull request merged**
