### PR TITLE
Texttool - Fix vertical shift on hit of confirm

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by punamdahiya** [comment]
Fixes #4620

**Comment by chenba** [comment]
Results on Windows 10, relative to master

Large font: No difference

Medium font: shifts up and maybe tiny bit to the right; font rendering blurry

Small font: shifts up noticeably and maybe tiny bit to the right

**Comment by chenba** [comment]
GIF (view at full size)

windows10-shifts

**Comment by punamdahiya** [comment]
@chenba updated PR to use styles.height and take rounding off y position to get rid off 0.5 height difference between clientHeight and styles.height.  does it help on windows 10?

**Comment by chenba** [comment]
All font sizes shift down on confirm now.

**Comment by punamdahiya** [comment]
@chenba from your previous comment it looks like on windows 10 we still don't have a marked improvement as compared to gif here 
https://github.com/mozilla-services/screenshots/issues/4620#issuecomment-406346339

**Comment by 6a68** [comment]
Closing without merging, as #4620 is good-enough.

**Pull request closed without merging**
