### PR TITLE
Allow self-hosting

### PR DESCRIPTION
**Pull request by 6a68**
Allows users to set the server URL via extensions.screenshots.server pred in about:config. Requires a restart currently.

### CODE REVIEW

**Comment by ianb** [comment]
Does this handle the permission and content script in manifest.json?

**Comment by 6a68** [comment]
> Does this handle the permission and content script in manifest.json?

Hmm. I tried setting a pref to point at localhost and screenshots.firefox.com, but I didn't try a random other domain. I'll do some /etc/hosts hacking locally and see if it works.

**Comment by ianb** [comment]
It looks like the CI failure will be fixed by merging master into this branch

**Comment by 6a68** [comment]
Closing for now

**Pull request closed without merging**
