### PR TITLE
Fixes #5089 - Screenshots keyboard shortcut

### LINKED ISSUE #5089: Add keyboard shortcut
We want to use Ctrl+Shift+S (or Command+Opt+S on Mac). This previously opened the devtools debugger, but that has been disabled (per [this comment](https://github.com/mozilla-services/screenshots/issues/2491#issuecomment-420007290)).

We'll need to open a Bugzilla ticket to remove this from devtools. We'll have to experiment with whether we can override it in our add-on before they remove it.

See also previous discussion in #2491

### PR DESCRIPTION
**Pull request by punamdahiya**
TIL Can't specify 'option' as a webextension hot key.
Just go with ctrl + shift + s, which will be command + shift + s on mac.

### CODE REVIEW

**Comment by punamdahiya** [comment]
@6a68 Updated WIP to refactor onClicked to use _startShotFlow and minor lint fixes. Cmd+Shift+ S works in Mac. On Linux and Windows Ctrl+Shift+S is still in use by devtools and open debugger. Marking PR on hold to land till we get access to shortcut on Windows and Linux. Thanks!

**Comment by punamdahiya** [comment]
Fixes #5089

**Comment by punamdahiya** [comment]
@digitarald Following on your feedback https://github.com/mozilla-services/screenshots/issues/2491#issuecomment-420012054, to use Ctrl + Shift + S for screenshots, can you please update what's the[ remaining steps needed](https://bugzilla.mozilla.org/show_bug.cgi?id=1502924) so that this shortcut is available. Thanks!

**Comment by 6a68** [comment]
@punamdahiya Maybe we can just fix bug 1502924 directly: https://bugzilla.mozilla.org/show_bug.cgi?id=1502924#c4

**Comment by 6a68** [comment]
Just clearing out my review queue. Cleared to land, but not sure we want to land anything else right now.

**Comment by 6a68** [comment]
@ianb Should we land this? Something positive to include along with the other changes?

**Comment by punamdahiya** [comment]
With https://bugzilla.mozilla.org/show_bug.cgi?id=1502924 and https://bugzilla.mozilla.org/show_bug.cgi?id=1514055 resolved, PR looks good to land. 


We should update mdn docs https://developer.mozilla.org/en-US/docs/Tools/Taking_screenshots once this fix lands

**Comment by ATLowther** [comment]
What version of Firefox has this been added to?

I am using Firefox Quantum 65.0.1 on a Mac and Command + Shift + S doesn't provide any obvious functionality.

I've also looked over the documentation a few comments up and none of the documentation seems to reference these shortcuts. Was integration of this shortcut abandoned?

@punamdahiya @6a68

**Comment by gijsk** [comment]
@ATLowther this landed in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1521168 and is being released as part of Firefox 67 (currently in beta).

**Pull request merged**
