### PR TITLE
Fix #4165 - Highlight color picker button on hover

### LINKED ISSUE #4165: [Annotations] "Color Picker" button is not highlighted when it's hovered
[Affected versions]:
- Nightly 60.0a1
- Screenshots 31.0.0 stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 31.0.0 stage version installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the browser and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Hover over the "Color Picker" button and observe the behavior.

[Expected result]:
- The button gains a hover effect.

[Actual result]:
- The button does not have a hover effect.

[Notes]:
- Here is a screenshot with the issue:
ss - color picker

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by punamdahiya** [comment]
@chenba git recommended you as reviewer, please let me know if I should send review request to someone else. Thanks!

**Comment by chenba** [comment]
@punamdahiya If you add "Fixes #4165" to the pull request's description, then that issue will be automatically closed when this is merged.  Github will also link this PR from #4165 when you do that.

**Comment by 6a68** [comment]
@punamdahiya Please let us know if you have any questions about getting this PR fixed up :+1:

**Comment by punamdahiya** [comment]
@6a68 Thanks Jared looking into implementing review feedback today, didn't get the notifications email from github because of a filter that I totally forgot about :)

**Comment by punamdahiya** [comment]
@chenba Thanks for review feedback, I have rebased PR with latest master and that should skip failing tests.
I investigated the 'click on picker button to close panel feature', that's the implemented behavior on master landed with fix of https://github.com/mozilla-services/screenshots/pull/4214

**Pull request merged**
