### PR TITLE
Fix-#2476-change privacy page to privacyLink

### LINKED ISSUE #2476: Update privacy links
All privacy links should link to: https://www.mozilla.org/privacy/websites/

The privacy content in the server itself should be removed.

### PR DESCRIPTION
**Pull request by cecilebertin**
This is a fix for Update privacy links.
Fixes #2476.

### CODE REVIEW

**Comment by 6a68** [comment]
@cecilebertin Hi there! Sorry for the delays in reviewing your pull requests; we're very focused on a major deadline at the end of this week.

I believe @Ianb was saying in IRC yesterday that we might need a separate privacy page just for Screenshots, and he needs to speak to Mozilla's legal team to confirm. So, this PR has to wait until we clarify the right approach. Thanks for your contributions so far :-)

**Comment by cecilebertin** [comment]
Hi @6a68!
No problem at all, I understand.

**Comment by ianb** [comment]
Sorry about the slowness on this, due to some changes from Legal.  

We'll probably have to revert this, but I want to land it for now since it's a good change and I like the thoroughness you brought to it, so this will put it on the record!

**Comment by cecilebertin** [comment]
Thank you @ianb !

**Pull request merged**
