### PR TITLE
Update ZAP command in circleci

### PR DESCRIPTION
**Pull request by jvehent**
This is a work in progress.

### CODE REVIEW

**Comment by jvehent** [comment]
The ZAP scan now runs correctly and returns the following warnings that we should address before merging this PR.
```
WARN-NEW: Cookie No HttpOnly Flag [10010] x 1 
	http://172.18.0.1:10080/shots

WARN-NEW: Web Browser XSS Protection Not Enabled [10016] x 4 
	http://172.18.0.1:10080/
	http://172.18.0.1:10080/robots.txt
	http://172.18.0.1:10080/sitemap.xml
	http://172.18.0.1:10080

WARN-NEW: Cross-Domain JavaScript Source File Inclusion [10017] x 4 
	http://172.18.0.1:10080/
	http://172.18.0.1:10080/robots.txt
	http://172.18.0.1:10080/sitemap.xml
	http://172.18.0.1:10080

WARN-NEW: Information Disclosure - Debug Error Messages [10023] x 2 
	http://172.18.0.1:10080/
	http://172.18.0.1:10080

WARN-NEW: Private IP Disclosure [2] x 1 
	http://172.18.0.1:10080/static/img/image-nope_screenshots.svg?rev=8.1.0-1152-g27243603

WARN-NEW: Application Error Disclosure [90022] x 2 
	http://172.18.0.1:10080/shots
	http://172.18.0.1:10080/static/js/homepage-bundle.js?rev=8.1.0-1152-g27243603
```

* 10010 requires httpOnly to be set on all cookies
* 10016 looks at the CSP which I presume is missing from robots.txt and sitemap.xml

@psiinon: can you advice on what needs to change for 10017, 10023, 2 and 90022 ?

**Comment by psiinon** [comment]
Kind of depends on what the details are ;)
Worth running again with the '-w report_md' option? Will write out the full report in md format.

**Comment by jvehent** [comment]
# ZAP Scanning Report




## Summary of Alerts

| Risk Level | Number of Alerts |
| --- | --- |
| High | 0 |
| Medium | 1 |
| Low | 7 |
| Informational | 1 |

## Alert Detail


  
  
  
### Application Error Disclosure
##### Medium (Medium)
  
  
  
  
#### Description
<p>This page contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception. This information can be used to launch further attacks against the web application. The alert could be a false positive if the error message is found inside a documentation page.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `internal error`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `internal error`
  
  
  
  
Instances: 2
  
### Solution
<p>Review the source code of this page. Implement custom error pages. Consider implementing a mechanism to provide a unique error reference/identifier to the client (browser) while logging the details on the server side and not exposing them to the user.</p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Cross-Domain JavaScript Source File Inclusion
##### Low (Medium)
  
  
  
  
#### Description
<p>The page includes one or more script files from a third-party domain.</p>
  
  
  
* URL: [https://screenshots.firefox.com/robots.txt](https://screenshots.firefox.com/robots.txt)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/sitemap.xml](https://screenshots.firefox.com/sitemap.xml)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
Instances: 5
  
### Solution
<p>Ensure JavaScript source files are loaded from only trusted sources, and the sources can't be controlled by end users of the application.</p>
  
### Reference
* 

  
#### CWE Id : 829
  
#### WASC Id : 15
  
#### Source ID : 3

  
  
  
### Incomplete or No Cache-control and Pragma HTTP Header Set
##### Low (Medium)
  
  
  
  
#### Description
<p>The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/css/simple.css?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/css/simple.css?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/css/shot-index.css?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/css/shot-index.css?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
Instances: 7
  
### Solution
<p>Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate; and that the pragma HTTP header is set with no-cache.</p>
  
### Reference
* https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching

  
#### CWE Id : 525
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Information Disclosure - Debug Error Messages
##### Low (Medium)
  
  
  
  
#### Description
<p>The response appeared to contain common error messages returned by platforms such as ASP.NET, and Web-servers such as IIS and Apache. You can configure the list of common debug messages.</p>
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
Instances: 3
  
### Solution
<p>Disable debugging messages before pushing to production.</p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Web Browser XSS Protection Not Enabled
##### Low (Medium)
  
  
  
  
#### Description
<p>Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server</p>
  
  
  
* URL: [https://screenshots.firefox.com/robots.txt](https://screenshots.firefox.com/robots.txt)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/sitemap.xml](https://screenshots.firefox.com/sitemap.xml)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
Instances: 5
  
### Solution
<p>Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'.</p>
  
### Other information
<p>The X-XSS-Protection HTTP response header allows the web server to enable or disable the web browser's XSS protection mechanism. The following values would attempt to enable it: </p><p>X-XSS-Protection: 1; mode=block</p><p>X-XSS-Protection: 1; report=http://www.example.com/xss</p><p>The following values would disable it:</p><p>X-XSS-Protection: 0</p><p>The X-XSS-Protection HTTP response header is currently supported on Internet Explorer, Chrome and Safari (WebKit).</p><p>Note that this alert is only raised if the response body could potentially contain an XSS payload (with a text-based content type, with a non-zero length).</p>
  
### Reference
* https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet
* https://blog.veracode.com/2014/03/guidelines-for-setting-security-headers/

  
#### CWE Id : 933
  
#### WASC Id : 14
  
#### Source ID : 3

  
  
  
### Cookie Without Secure Flag
##### Low (Medium)
  
  
  
  
#### Description
<p>A cookie has been set without the secure flag, which means that the cookie can be accessed via unencrypted connections.</p>
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `_csrf`
  
  
  * Evidence: `set-cookie: _csrf`
  
  
  
  
Instances: 1
  
### Solution
<p>Whenever a cookie contains sensitive information or is a session token, then it should always be passed using an encrypted channel. Ensure that the secure flag is set for cookies containing such sensitive information.</p>
  
### Reference
* http://www.owasp.org/index.php/Testing_for_cookies_attributes_(OWASP-SM-002)

  
#### CWE Id : 614
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Private IP Disclosure
##### Low (Medium)
  
  
  
  
#### Description
<p>A private IP (such as 10.x.x.x, 172.x.x.x, 192.168.x.x) or an Amazon EC2 private hostname (for example, ip-10-0-56-78) has been found in the HTTP response body. This information might be helpful for further attacks targeting internal systems.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `10.8.1.2`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `10.8.1.2`
  
  
  
  
Instances: 2
  
### Solution
<p>Remove the private IP address from the HTTP response body.  For comments, use JSP/ASP/PHP comment instead of HTML/JavaScript comment which can be seen by client browsers.</p>
  
### Other information
<p>10.8.1.2</p><p></p>
  
### Reference
* https://tools.ietf.org/html/rfc1918

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Cookie No HttpOnly Flag
##### Low (Medium)
  
  
  
  
#### Description
<p>A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.</p>
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `_csrf`
  
  
  * Evidence: `set-cookie: _csrf`
  
  
  
  
Instances: 1
  
### Solution
<p>Ensure that the HttpOnly flag is set for all cookies.</p>
  
### Reference
* http://www.owasp.org/index.php/HttpOnly

  
#### CWE Id : 16
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Information Disclosure - Suspicious Comments
##### Informational (Medium)
  
  
  
  
#### Description
<p>The response appears to contain suspicious comments which may help an attacker.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/js/wantsauth.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/wantsauth.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/install-raven.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/install-raven.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/ga-activation.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/ga-activation.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
Instances: 9
  
### Solution
<p>Remove all comments that return information that may help an attacker and fix any underlying problems they refer to.</p>
  
### Other information
<p>  // is special logic for view pages where ownership is interesting in addition to</p><p></p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

**Comment by jvehent** [comment]
# ZAP Scanning Report




## Summary of Alerts

| Risk Level | Number of Alerts |
| --- | --- |
| High | 0 |
| Medium | 1 |
| Low | 7 |
| Informational | 1 |

## Alert Detail


  
  
  
### Application Error Disclosure
##### Medium (Medium)
  
  
  
  
#### Description
<p>This page contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception. This information can be used to launch further attacks against the web application. The alert could be a false positive if the error message is found inside a documentation page.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `internal error`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `internal error`
  
  
  
  
Instances: 2
  
### Solution
<p>Review the source code of this page. Implement custom error pages. Consider implementing a mechanism to provide a unique error reference/identifier to the client (browser) while logging the details on the server side and not exposing them to the user.</p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Cross-Domain JavaScript Source File Inclusion
##### Low (Medium)
  
  
  
  
#### Description
<p>The page includes one or more script files from a third-party domain.</p>
  
  
  
* URL: [https://screenshots.firefox.com/robots.txt](https://screenshots.firefox.com/robots.txt)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com/sitemap.xml](https://screenshots.firefox.com/sitemap.xml)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `//www.google-analytics.com/analytics.js`
  
  
  * Evidence: `<script src="//www.google-analytics.com/analytics.js" async=""></script>`
  
  
  
  
Instances: 5
  
### Solution
<p>Ensure JavaScript source files are loaded from only trusted sources, and the sources can't be controlled by end users of the application.</p>
  
### Reference
* 

  
#### CWE Id : 829
  
#### WASC Id : 15
  
#### Source ID : 3

  
  
  
### Incomplete or No Cache-control and Pragma HTTP Header Set
##### Low (Medium)
  
  
  
  
#### Description
<p>The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/css/simple.css?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/css/simple.css?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/css/shot-index.css?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/css/shot-index.css?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  * Evidence: `public, max-age=86400`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `Cache-Control`
  
  
  
  
Instances: 7
  
### Solution
<p>Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate; and that the pragma HTTP header is set with no-cache.</p>
  
### Reference
* https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching

  
#### CWE Id : 525
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Information Disclosure - Debug Error Messages
##### Low (Medium)
  
  
  
  
#### Description
<p>The response appeared to contain common error messages returned by platforms such as ASP.NET, and Web-servers such as IIS and Apache. You can configure the list of common debug messages.</p>
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Evidence: `Internal server error`
  
  
  
  
Instances: 3
  
### Solution
<p>Disable debugging messages before pushing to production.</p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Web Browser XSS Protection Not Enabled
##### Low (Medium)
  
  
  
  
#### Description
<p>Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server</p>
  
  
  
* URL: [https://screenshots.firefox.com/robots.txt](https://screenshots.firefox.com/robots.txt)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/sitemap.xml](https://screenshots.firefox.com/sitemap.xml)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `X-XSS-Protection`
  
  
  
  
Instances: 5
  
### Solution
<p>Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'.</p>
  
### Other information
<p>The X-XSS-Protection HTTP response header allows the web server to enable or disable the web browser's XSS protection mechanism. The following values would attempt to enable it: </p><p>X-XSS-Protection: 1; mode=block</p><p>X-XSS-Protection: 1; report=http://www.example.com/xss</p><p>The following values would disable it:</p><p>X-XSS-Protection: 0</p><p>The X-XSS-Protection HTTP response header is currently supported on Internet Explorer, Chrome and Safari (WebKit).</p><p>Note that this alert is only raised if the response body could potentially contain an XSS payload (with a text-based content type, with a non-zero length).</p>
  
### Reference
* https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet
* https://blog.veracode.com/2014/03/guidelines-for-setting-security-headers/

  
#### CWE Id : 933
  
#### WASC Id : 14
  
#### Source ID : 3

  
  
  
### Cookie Without Secure Flag
##### Low (Medium)
  
  
  
  
#### Description
<p>A cookie has been set without the secure flag, which means that the cookie can be accessed via unencrypted connections.</p>
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `_csrf`
  
  
  * Evidence: `set-cookie: _csrf`
  
  
  
  
Instances: 1
  
### Solution
<p>Whenever a cookie contains sensitive information or is a session token, then it should always be passed using an encrypted channel. Ensure that the secure flag is set for cookies containing such sensitive information.</p>
  
### Reference
* http://www.owasp.org/index.php/Testing_for_cookies_attributes_(OWASP-SM-002)

  
#### CWE Id : 614
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Private IP Disclosure
##### Low (Medium)
  
  
  
  
#### Description
<p>A private IP (such as 10.x.x.x, 172.x.x.x, 192.168.x.x) or an Amazon EC2 private hostname (for example, ip-10-0-56-78) has been found in the HTTP response body. This information might be helpful for further attacks targeting internal systems.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-nope_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `10.8.1.2`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/img/image-search_screenshots.svg?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  * Evidence: `10.8.1.2`
  
  
  
  
Instances: 2
  
### Solution
<p>Remove the private IP address from the HTTP response body.  For comments, use JSP/ASP/PHP comment instead of HTML/JavaScript comment which can be seen by client browsers.</p>
  
### Other information
<p>10.8.1.2</p><p></p>
  
### Reference
* https://tools.ietf.org/html/rfc1918

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Cookie No HttpOnly Flag
##### Low (Medium)
  
  
  
  
#### Description
<p>A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.</p>
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  * Parameter: `_csrf`
  
  
  * Evidence: `set-cookie: _csrf`
  
  
  
  
Instances: 1
  
### Solution
<p>Ensure that the HttpOnly flag is set for all cookies.</p>
  
### Reference
* http://www.owasp.org/index.php/HttpOnly

  
#### CWE Id : 16
  
#### WASC Id : 13
  
#### Source ID : 3

  
  
  
### Information Disclosure - Suspicious Comments
##### Informational (Medium)
  
  
  
  
#### Description
<p>The response appears to contain suspicious comments which may help an attacker.</p>
  
  
  
* URL: [https://screenshots.firefox.com/static/js/wantsauth.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/wantsauth.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/install-raven.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/install-raven.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/ga-activation.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/ga-activation.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/shotindex-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/shots](https://screenshots.firefox.com/shots)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com](https://screenshots.firefox.com)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3](https://screenshots.firefox.com/static/js/homepage-bundle.js?rev=8.1.0-1011-gfd4b2b3)
  
  
  * Method: `GET`
  
  
  
  
* URL: [https://screenshots.firefox.com/](https://screenshots.firefox.com/)
  
  
  * Method: `GET`
  
  
  
  
Instances: 9
  
### Solution
<p>Remove all comments that return information that may help an attacker and fix any underlying problems they refer to.</p>
  
### Other information
<p>  // is special logic for view pages where ownership is interesting in addition to</p><p></p>
  
### Reference
* 

  
#### CWE Id : 200
  
#### WASC Id : 13
  
#### Source ID : 3

**Comment by psiinon** [comment]
Note that we can whitelist google-analytics and other 3rd party sites we want to use via baseline configs

**Comment by jvehent** [comment]
@ianb This now passes and runs a baseline security in circleci. Care to merge it?

**Comment by 6a68** [comment]
Git history looks a little funky. I'll rebase and then land this. Thanks for your help, @jvehent :beers:

**Comment by jvehent** [comment]
Thanks @6a68 . I see the built failed on `npm test` but passed the baseline, so this is probably unrelated to this patch.

**Comment by 6a68** [comment]
Yup, looks like a rebuild did the trick. Merging

**Pull request merged**
