### PR TITLE
Fix #3450: Re-enable eslint-plugin-mozilla now that it is fixed.

### LINKED ISSUE #3450: Put mozilla eslint rules back in
@Standard8 is looking at the problems we've encountered.

Commit 2d01ca1864006c0d0158edeff60a8984ec64a6b2 removed the use of the mozilla plugins; undoing that commit should put things back.

### PR DESCRIPTION
**Pull request by Standard8**

### CODE REVIEW

**Comment by Standard8** [comment]
@ianb Any idea how I can get around the node-sass failure here? I was trying to upgrade the node version you're running to pick up a later npm to help fix the dependency issues circleci was seeing...

**Comment by 6a68** [comment]
@Standard8 Supposedly (https://github.com/sass/node-sass/issues/1985) the node-sass error is fixed, might need to ping the circle-ci people to figure out what's up there.

But note that I'm getting the dreaded "Cannot read property 'ecmaFeatures' of undefined" error locally when running eslint against this branch, with node 8.5.0 and npm 5.3.0 ;_;

**Comment by ianb** [comment]
The CI problem was some cached Node packages, rebuilding without cache fixed it.

**Comment by 6a68** [comment]
Got it to pass after doing `rm -rf node_modules && npm install && npm run lint:js` twice. First time, I randomly got some error about eslint-plugin-react not being found. Whatever, merging

**Comment by 6a68** [comment]
Ah, Ian beat me to it :beers:

**Pull request merged**
