### PR TITLE
Advise using push -f to release to server-prod, I've made too many mistakes with merging

### PR DESCRIPTION
**Pull request by ianb**
In anticipation I've already turned off the protected branch.

The `ours` merge strategy only makes things worse IMHO, as it lets things proceed dangerously. OTOH, conflict resolution is also always the wrong thing. `push -f` is genuinely the right thing to do.

### CODE REVIEW

**Comment by 6a68** [comment]
If we can't keep a long-running server-prod branch updated cleanly, why do we have such a branch? Why not just tag master and release from the tag?

**Comment by ianb** [comment]
Tagging would be better, yes, this just documents what works now. We need some scheme to indicate a candidate server tag, and then update the circleci config to trigger the release based on a tag that matches that scheme.

**Comment by ianb** [comment]
It's a little obtuse, but I added instructions to disable then enable branch protection.

**Comment by hwine** [comment]
@ianb Can you describe, or point to, what challenges or errors you ran into with the "ours" strategy? 

If I can't "fix" things, I'd at least like to [warn others](https://wiki.mozilla.org/GitHub/Repository_Security/Problems_and_Options#Problem:_Our_workflow_uses_force_pushes_to_production_to_ensure_we_know_what_will_be_deployed.)

As always, there are tradeoffs -- our main goal is to ensure we get the "best fit" for each project.

**Pull request merged**
