### PR TITLE
Fix #2140 "Remove Page Shot data" page is wrongly titled as "Confirm account deletion" 

### LINKED ISSUE #2140: The "Remove Page Shot data" page is wrongly titled as "Confirm account deletion"
[Affected versions]:
- Firefox 51 and up
- Mozilla Page Shot 5.2.201701261556

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest version of the Page Shot add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any page.
2. Click on the Page Shot button from the browser toolbar.
3. Click the "My Shots" button.
4. Click the "Remove all Data" from the bottom right part of the page.
5. Observe the tab title.

[Expected result]:
- The tab title reflects data deletion process.

[Actual result]:
- The tab title is "Confirm account deletion".

[Notes]:
- Here is a screen recording with the issue: 
remove page shot data tab

### PR DESCRIPTION
**Pull request by gvanwaelvelde**
The "Remove Page Shot data" page was wrongly titled as "Confirm account deletion" 
I changed it to "Remove All Data".

### CODE REVIEW

**Comment by gvanwaelvelde** [comment]
Hello @6a68 ,
Thanks for the quick review!
I've renamed the key in the server.ftl file. Is that enough? Or do I need to make changes elsewhere as well? I don't seem to find any references to this key, except in other localizations of server.ftl

**Comment by 6a68** [comment]
@gvanwaelvelde Hmm, looks like that key's not used anywhere. Feel free to remove it :-P

**Comment by gvanwaelvelde** [comment]
I changed it back. Now's it's good to go, I guess?

**Comment by 6a68** [comment]
@gvanwaelvelde I've got your branch running locally, and it seems like there's currently no title set on the 'leave-screenshots' page (note the tab just shows the URL):

screen shot 2017-08-04 at 2 46 04 pm

Looks like the wrong l10n ID is set [in the `leave-screenshots` model](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/leave-screenshots/model.js#L4):

```js
// server/src/pages/leave-screenshots/model.js
exports.createModel = function(req) {
  let complete = "complete" in req.query;
  return {
    title: req.getText("leavePageConfirmDeletion"), // <--- this ID is wrong
    complete
  };
};
```

Would you mind (1) reverting the .ftl file changes and (2) updating that model to instead pass the correct l10n ID, "leavePageConfirmDelete"? Here's how you can double-check that this fixes the bug:
1. start the server locally: `./bin/run-server`
2. start a copy of Nightly with Screenshots pointed at localhost: `./bin/run-addon --bootstrap`
3. create a shot
4. from the shot page, click the 'remove all data' link in the footer
5. at the leave-screenshots URL, you should see 'Remove All Data' in the title

Sorry I missed this on the first pass, and thanks again for contributing :+1:

**Comment by gvanwaelvelde** [comment]
I've changed the l10n ID in model.js.
I don't quite understand which changes to server.ftl should be reverted?

**Comment by 6a68** [comment]
@gvanwaelvelde Looks good, just need to update one more thing: change the server.ftl string ID from `leavePageConfirmDelete` to `leavePageRemoveAllData`, and make the same change in the model.js file. And then I will happily, finally, merge your PR :-)

**Comment by gvanwaelvelde** [comment]
@6a68 I made the changes you requested.

**Comment by 6a68** [comment]
@gvanwaelvelde 🎉

**Pull request merged**
