### PR TITLE
scssfile

### PR DESCRIPTION
**Pull request by silkypriya**
Encapsulate text tool styles using sass nesting.

### CODE REVIEW

**Comment by chenba** [comment]
Fix #4701

**Comment by chenba** [comment]
@silkypriya Thanks for the patch!  It works, but could you nest all the colors in just one declaration of `.textTool`, i.e.:

```
.textTool {
  .black {
    ...
  }
  .white {
    ...
  }
  ...
}
```
?

**Comment by silkypriya** [comment]
Hi, @chenba, I have made the suggested changes. Please take a look, thanks!

**Comment by chenba** [comment]
@silkypriya I've squashed the commits and merged your patch.  Thanks!

**Pull request merged**
