### PR TITLE
Fixes #4712 - TextInput shows 5px edge limit on max width

### LINKED ISSUE #4712: [Annotations] [Texttool] Align textbox to show 5px edge limit on right when it reaches max width
Fix of #4680, limits content entered in input text. 

When a user enters a long string textbox touches the right edge.  https://github.com/mozilla-services/screenshots/pull/4708#issuecomment-408235842

On drag the text input displays 5px edge limit. Opening the issue to optimize left position of input text to leave minimum 5px edge limit on right while typing in and pasting long string.

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by punamdahiya** [comment]
@chenba PR fixes text touching canvas on right edge on typing or pasting long string. Fix account for 5px edge while calculating left position on component mount. Thanks

**Comment by punamdahiya** [comment]
Updated to remove INIT_FONT_SIZE while computing init left position https://github.com/mozilla-services/screenshots/pull/4720/files#diff-9f381191523a3625a937e1c5ca297f1fR43

**Comment by chenba** [comment]
If you rebase on latest master, the tests should pass.

**Comment by punamdahiya** [comment]
PR rebased with latest master

**Pull request merged**
