### PR TITLE
Shutdown the embedded webExtension when bootstrap is asked to shutdown

### PR DESCRIPTION
**Pull request by ianb**
@rhelmer or @6a68

### CODE REVIEW

**Comment by rhelmer** [comment]
lgtm, this is almost exactly what I tested locally.

**Comment by 6a68** [comment]
@ianb This looks good. Sadly, I think we need to change the "if reason == APP_STARTUP" bit from the startup method--otherwise I think the pref observer will stop working when the addon is upgraded. Would you mind setting a flag when the observer is registered, then checking that flag, instead of the reason constant, inside startup? We always want exactly one listener.

**Comment by ianb** [comment]
@6a68 I'm not sure I understand.  `if (reason === APP_STARTUP)` only protects `appStartupObserver.register()` (which seems to unregister itself).  But it doesn't stop the rest of startup() from being called, including the pref observer.  Unless I miss what you are thinking about here.

**Comment by 6a68** [comment]
@ianb Ah yeah, you're right! Sorry about that, merging

**Pull request merged**
