### PR TITLE
Catch Watchdog upstream error

### LINKED ISSUE #4871: [Watchdog] Handle error in Watchdog Response
After https://github.com/mozilla/watchdog-proxy/pull/185, Watchdog will include an `error` in its response to indicate whether PhotoDNA reported an error.  We need to use this property to prevent marking a shot as a false negative.

### PR DESCRIPTION
**Pull request by chenba**
Fixes #4871

### CODE REVIEW

**Comment by chenba** [comment]
I'll file an issue in Watchdog to document its responses.

As for (intergration) testing, there's no simple way.  We could a) mock a Watchdog service to give us the responses we want to test, b) configure a Watchdog instance to give us the responses we want to test, or c) mock a PhotoDNA service to throw the errors we want.  😩

Could use mocks to unit test to see if the correct errors are thrown.

**Comment by chenba** [comment]
Oh for manual verification, one could try uploading a shot that's >4MB.  But since the result is really a no-op, we'd need to check Sentry for the error.

**Comment by 6a68** [comment]
@chenba Cool. Do you think it'd be easy to mock out Watchdog for local testing?

**Comment by 6a68** [comment]
Doh, missed your earlier comment :-P

**Comment by chenba** [comment]
Filed #4931 for writing tests for Watchdog integration.

**Pull request merged**
