### PR TITLE
extended direct-view event with ownership

### LINKED ISSUE #2143: Implement event label to distinguish between owner and non-owner direct-views
currently we have `web/visit/direct-view`, let's split this out into `web/visit/direct-view-owner` and `web/visit/direct-view-non-owner`

### PR DESCRIPTION
**Pull request by dannycoates**
closes #2143

### CODE REVIEW

**Comment by dannycoates** [comment]
Are we planning on using a CDN for screenshots? I was under the impression that we'll only be using one for site assets.

**Comment by ianb** [comment]
Yes, we were planning on using a CDN (under a separate domain name) for individual images, not just site assets.

**Comment by dannycoates** [comment]
> we were planning on using a CDN (under a separate domain name) for individual images

I think there's more work for this that doesn't have tracking issues like invalidating the CDN cache when the conditions used in the query for [getRawBytesForClip](https://github.com/mozilla-services/screenshots/blob/master/server/src/servershot.js#L303) change (block, delete, expire).

Secondarily, do we have evidence that CDNifying the screenshots will be worth the expense? My uneducated guess is that most shots aren't generally accessed by a large distribution of users. Maybe a simple http cache (nginx, varnish) would be enough. I guess I'm saying I don't understand the expectations / requirements.

cc #2210

**Comment by ianb** [comment]
You're right, there are important implications to the CDN.  @relud did some calculations that using a CDN wouldn't be any more expensive than serving the images directly, even if the images weren't accessed in any volume.

**Comment by dannycoates** [comment]
There's also the complexity cost. I'm not against it if it makes sense, I just want to understand the cost / benefits.

**Pull request merged**
