### PR TITLE
Fix last step in fxa oauth flow

### PR DESCRIPTION
**Pull request by 6a68**
*Edited: this PR is now a complete fix for #3681.*

Partial fix for #3681. The implementation of the `request` and `readBody` methods inside `helpers.js` assumed that the wrapped `wreck` methods were callback-based, but those methods actually return promises, so the promise chain wasn't terminated properly. I don't see any need for the helpers, so just invoked the `wreck` methods directly.

@niharikak101 Does this unblock you with fxa debugging?

Without this patch, when I do the fxa login flow on localhost, it hangs forever after entering the password and confirmation code. (When I do the same on the dev server, as in the STR for #3681, I see a 504 Gateway Timeout after a 60 second wait, which I think is nginx timing out the connection.)

With this patch, when I do the fxa login flow on localhost, I immediately get a 403 error with message "Invalid OAuth access token".

Doesn't fix FxA, but does move the debugging one step forward :+1:

### CODE REVIEW

**Comment by niharikak101** [comment]
Thank you for taking the time to look at this, @6a68! Definitely helped to identify the root of the problem. I tried using `node-fetch` instead of `wreck` which is a lot simpler and also has support for `promises`. The oAuth flow is working as expected; I'm adding a new commit to this PR.

**Comment by 6a68** [comment]
sweet! Thanks for adding that commit, @niharikak101.

**Comment by 6a68** [comment]
wow! this indeed fixes fxa locally: I can connect one profile to fxa, then log in from a new scratch profile, log in with that account, and access the shots.

**Comment by ianb** [comment]
Looks good – too late now, but it would have been a reasonable place to start using async/await.

**Pull request merged**
