### PR TITLE
update acceptance for fxa

### PR DESCRIPTION
**Pull request by johngruen**
#Fixes 3469

### CODE REVIEW

**Comment by chenba** [comment]
Fixes #3469.  (There's typo in the description.)

**Comment by chenba** [comment]
I'm changing base branch to `fxa-integration` since that's where the FxA features are being developed.

**Comment by johngruen** [comment]
Changing branches brought in some l10n but i guess that's okay...feel free to merge if there are no changes u need

**Comment by chenba** [comment]
I'll cherry-pick and force push for a cleaner PR.

**Pull request merged**
