### PR TITLE
[WIP] Canvas toblob

### PR DESCRIPTION
**Pull request by ianb**
Note: this isn't ready to land

* Requires some cleanup, console.log removal.
* URL.createObjectURL needs to have its urls revoked.
* Local download may be broken

### CODE REVIEW

**Comment by chenba** [comment]
Seems to work just fine, including local downloads.  `console.log`s were removed during teh merge.

**Comment by 6a68** [comment]
@ianb Want to rebase and attempt to land this, or close it?

**Comment by 6a68** [comment]
Closing. Let's reopen when it's rebased

**Comment by 6a68** [comment]
Hey, looks like this could fix the Blob URL issue. Reopening, I'll get this ready to land

**Comment by 6a68** [comment]
aha! I reopened this. reclosing till I have time to fix it up

**Pull request closed without merging**
