### PR TITLE
Fix WebExtension Initialization in packaged builds.

### PR DESCRIPTION
**Pull request by Standard8**
Dropping the QI seems to work.

I suggest not merging this, until we get a clean try run, just in case ;-)

### CODE REVIEW

**Comment by Standard8** [comment]
A full try push is here:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=ea620bdca2cd6520186be95dbc7f987e164be4c4

**Comment by 6a68** [comment]
¯\_(ツ)_/¯ I don't even know. r+ from me, feel free to self-merge once you get the Try results

**Comment by 6a68** [comment]
@Standard8 OK, this is truly bizarre. On my machine, when I run the `browser/modules/test/browser/browser_BrowserUITelemetry_defaults.js` test, the webextension button is inserted to the left of the Pocket button, and the test passes.

On the Try server, the Pocket button is rendered later, to the right of the Screenshots button, and that's why the test fails with 'CUI in a dirty state'.

I swapped the order of the navbar placements in CUI.jsm and pushed that change to Try. We'll see if that fixes it on all platforms...although I suspect there's a race condition at play. Try link: https://treeherder.mozilla.org/#/jobs?repo=try&revision=6e9cbaa1d9249d069e085031174d8154b02294a2

**Comment by 6a68** [comment]
Here's a screenshot of the `browser/modules/test/browser/browser_BrowserUITelemetry_defaults.js` test on my machine, note the order of the Pocket and Screenshots buttons:

screen shot 2017-04-05 at 10 34 12 am

And here's a link to an image from your failing Try build (linux x64 opt bc5), which shows the button order is inverted: https://public-artifacts.taskcluster.net/Z9ead8v9R86OU276ZjeCLg/0/public/test_info//mozilla-test-fail-screenshot__vQbfb.png

**Comment by 6a68** [comment]
Welp, it looks like my Try job from a couple comments back passed on linux, except for two known unrelated oranges. Hopefully win64 and mac64 will be green as well.

**Comment by 6a68** [comment]
Regardless of the other try runs, this seems like a good change, so I'm going to land it.

**Pull request merged**
